"""Tests for Item 08 — Parametric Generation.

Covers: ElementGenerator, all builders, folder output, template-based
generation, compliance integration, and assembly generation.
"""

from __future__ import annotations

import json
from pathlib import Path

import pytest

from aecos.compliance.engine import ComplianceEngine
from aecos.generation.assembly import AssemblyGenerator
from aecos.generation.builders import get_builder
from aecos.generation.builders.beam import BeamBuilder
from aecos.generation.builders.column import ColumnBuilder
from aecos.generation.builders.door import DoorBuilder
from aecos.generation.builders.slab import SlabBuilder
from aecos.generation.builders.wall import WallBuilder
from aecos.generation.builders.window import WindowBuilder
from aecos.generation.generator import ElementGenerator
from aecos.nlp.schema import ParametricSpec


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _wall_spec(**overrides) -> ParametricSpec:
    defaults = dict(
        intent="create",
        ifc_class="IfcWall",
        name="Test Wall",
        properties={"thickness_mm": 200.0, "height_mm": 3000.0, "length_mm": 5000.0},
        materials=["concrete"],
        performance={"fire_rating": "2H"},
    )
    defaults.update(overrides)
    return ParametricSpec(**defaults)


def _verify_folder_structure(folder: Path) -> None:
    """Verify the folder matches Item 01 extraction format."""
    assert folder.is_dir()
    assert (folder / "metadata.json").is_file()
    assert (folder / "properties" / "psets.json").is_file()
    assert (folder / "materials" / "materials.json").is_file()
    assert (folder / "geometry" / "shape.json").is_file()
    assert (folder / "relationships" / "spatial.json").is_file()
    assert (folder / "element.ifc").is_file()
    # Markdown files (generated by metadata layer)
    assert (folder / "README.md").is_file()


def _load_json(path: Path) -> dict | list:
    return json.loads(path.read_text(encoding="utf-8"))


# ---------------------------------------------------------------------------
# Builder Tests
# ---------------------------------------------------------------------------

class TestBuilders:
    """Test individual element builders."""

    def test_wall_builder_psets(self):
        b = WallBuilder()
        psets = b.build_psets(
            {"thickness_mm": 200, "height_mm": 3000, "length_mm": 5000},
            {"fire_rating": "2H"},
        )
        assert "Pset_WallCommon" in psets
        assert psets["Pset_WallCommon"]["FireRating"] == "2H"
        assert "Dimensions" in psets
        assert psets["Dimensions"]["thickness_mm"] == 200

    def test_wall_builder_materials(self):
        b = WallBuilder()
        mats = b.build_materials(["concrete"], {"thickness_mm": 200})
        assert len(mats) == 1
        assert mats[0]["name"] == "concrete"
        assert mats[0]["thickness"] == 200

    def test_wall_builder_multi_layer(self):
        b = WallBuilder()
        mats = b.build_materials(["brick", "insulation", "gypsum"], {"thickness_mm": 300})
        assert len(mats) == 3
        assert mats[0]["thickness"] == 100.0

    def test_wall_builder_geometry(self):
        b = WallBuilder()
        geo = b.build_geometry({"thickness_mm": 200, "height_mm": 3000, "length_mm": 5000})
        assert geo["volume"] > 0
        bb = geo["bounding_box"]
        assert bb["max_x"] == pytest.approx(5.0)
        assert bb["max_z"] == pytest.approx(3.0)

    def test_door_builder(self):
        b = DoorBuilder()
        assert b.ifc_class == "IfcDoor"
        psets = b.build_psets({"width_mm": 914, "height_mm": 2134}, {})
        assert psets["Dimensions"]["width_mm"] == 914
        mats = b.build_materials([], {})
        assert mats[0]["name"] == "Wood"
        geo = b.build_geometry({"width_mm": 914, "height_mm": 2134})
        assert geo["volume"] > 0

    def test_window_builder(self):
        b = WindowBuilder()
        assert b.ifc_class == "IfcWindow"
        psets = b.build_psets({"width_mm": 1200}, {"thermal_u_value": 1.5})
        assert "Pset_WindowCommon" in psets
        assert psets["Pset_WindowCommon"]["ThermalTransmittance"] == 1.5

    def test_slab_builder(self):
        b = SlabBuilder()
        assert b.ifc_class == "IfcSlab"
        geo = b.build_geometry({"thickness_mm": 200, "length_mm": 6000, "width_mm": 6000})
        assert geo["volume"] == pytest.approx(7.2, abs=0.1)

    def test_column_builder_rectangular(self):
        b = ColumnBuilder()
        assert b.ifc_class == "IfcColumn"
        psets = b.build_psets({"width_mm": 400, "height_mm": 3600}, {})
        assert psets["Dimensions"]["shape"] == "rectangular"

    def test_column_builder_circular(self):
        b = ColumnBuilder()
        geo = b.build_geometry({"width_mm": 400, "height_mm": 3600, "shape": "circular", "diameter_mm": 400})
        assert geo["volume"] > 0
        assert geo["bounding_box"]["max_z"] == pytest.approx(3.6)

    def test_beam_builder(self):
        b = BeamBuilder()
        assert b.ifc_class == "IfcBeam"
        psets = b.build_psets({"depth_mm": 500, "width_mm": 300, "length_mm": 6000}, {})
        assert psets["Dimensions"]["profile_type"] == "W"

    def test_get_builder_registry(self):
        assert isinstance(get_builder("IfcWall"), WallBuilder)
        assert isinstance(get_builder("IfcDoor"), DoorBuilder)
        assert isinstance(get_builder("IfcWindow"), WindowBuilder)
        assert isinstance(get_builder("IfcSlab"), SlabBuilder)
        assert isinstance(get_builder("IfcColumn"), ColumnBuilder)
        assert isinstance(get_builder("IfcBeam"), BeamBuilder)
        # Unknown class falls back to WallBuilder
        assert isinstance(get_builder("IfcFoo"), WallBuilder)


# ---------------------------------------------------------------------------
# Generator Tests
# ---------------------------------------------------------------------------

class TestElementGenerator:
    """Test the ElementGenerator end-to-end."""

    def test_generate_wall(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = _wall_spec()
        folder = gen.generate(spec)
        _verify_folder_structure(folder)

        meta = _load_json(folder / "metadata.json")
        assert meta["IFCClass"] == "IfcWall"
        assert meta["Name"] == "Test Wall"

        psets = _load_json(folder / "properties" / "psets.json")
        assert "Pset_WallCommon" in psets
        assert psets["Pset_WallCommon"]["FireRating"] == "2H"

        mats = _load_json(folder / "materials" / "materials.json")
        assert len(mats) == 1
        assert mats[0]["name"] == "concrete"

        geo = _load_json(folder / "geometry" / "shape.json")
        assert geo["volume"] > 0

    def test_generate_door(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = ParametricSpec(
            ifc_class="IfcDoor",
            name="Test Door",
            properties={"width_mm": 914, "height_mm": 2134},
            materials=["wood"],
        )
        folder = gen.generate(spec)
        _verify_folder_structure(folder)
        meta = _load_json(folder / "metadata.json")
        assert meta["IFCClass"] == "IfcDoor"

    def test_generate_window(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = ParametricSpec(
            ifc_class="IfcWindow",
            properties={"width_mm": 1200, "height_mm": 1500},
            materials=["glass"],
        )
        folder = gen.generate(spec)
        _verify_folder_structure(folder)

    def test_generate_slab(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = ParametricSpec(
            ifc_class="IfcSlab",
            properties={"thickness_mm": 200, "length_mm": 6000, "width_mm": 6000},
            materials=["concrete"],
        )
        folder = gen.generate(spec)
        _verify_folder_structure(folder)

    def test_generate_column(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = ParametricSpec(
            ifc_class="IfcColumn",
            properties={"width_mm": 400, "height_mm": 3600},
            materials=["concrete"],
        )
        folder = gen.generate(spec)
        _verify_folder_structure(folder)

    def test_generate_beam(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = ParametricSpec(
            ifc_class="IfcBeam",
            properties={"depth_mm": 500, "width_mm": 300, "length_mm": 6000},
            materials=["steel"],
        )
        folder = gen.generate(spec)
        _verify_folder_structure(folder)

    def test_metadata_json_populated(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = _wall_spec()
        folder = gen.generate(spec)
        meta = _load_json(folder / "metadata.json")
        assert "GlobalId" in meta
        assert meta["GlobalId"] != ""
        assert "Name" in meta
        assert "IFCClass" in meta

    def test_psets_json_populated(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = _wall_spec()
        folder = gen.generate(spec)
        psets = _load_json(folder / "properties" / "psets.json")
        assert "Pset_WallCommon" in psets
        assert "Dimensions" in psets

    def test_materials_json_populated(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = _wall_spec(materials=["brick", "insulation"])
        folder = gen.generate(spec)
        mats = _load_json(folder / "materials" / "materials.json")
        assert len(mats) == 2

    def test_spatial_json_populated(self, tmp_path: Path):
        gen = ElementGenerator(tmp_path)
        spec = _wall_spec()
        folder = gen.generate(spec)
        spatial = _load_json(folder / "relationships" / "spatial.json")
        assert isinstance(spatial, dict)


# ---------------------------------------------------------------------------
# Template-Based Generation
# ---------------------------------------------------------------------------

class TestTemplateGeneration:
    """Test generate_from_template."""

    def _make_template(self, path: Path) -> Path:
        """Create a mock template folder."""
        folder = path / "template_test"
        folder.mkdir(parents=True)

        meta = {"GlobalId": "TMPL001", "Name": "Template Wall", "IFCClass": "IfcWall"}
        (folder / "metadata.json").write_text(json.dumps(meta), encoding="utf-8")

        props_dir = folder / "properties"
        props_dir.mkdir()
        psets = {"Pset_WallCommon": {"IsExternal": True}, "Dimensions": {"thickness_mm": 150, "height_mm": 3000, "length_mm": 5000}}
        (props_dir / "psets.json").write_text(json.dumps(psets), encoding="utf-8")

        mat_dir = folder / "materials"
        mat_dir.mkdir()
        (mat_dir / "materials.json").write_text(json.dumps([{"name": "concrete", "thickness": 150}]), encoding="utf-8")

        geo_dir = folder / "geometry"
        geo_dir.mkdir()
        (geo_dir / "shape.json").write_text(json.dumps({"bounding_box": {}, "volume": 0}), encoding="utf-8")

        rel_dir = folder / "relationships"
        rel_dir.mkdir()
        (rel_dir / "spatial.json").write_text(json.dumps({}), encoding="utf-8")

        return folder

    def test_generate_from_template(self, tmp_path: Path):
        template = self._make_template(tmp_path)
        output = tmp_path / "output"
        gen = ElementGenerator(output)
        folder = gen.generate_from_template(template, overrides={"thickness_mm": 250})
        _verify_folder_structure(folder)

        psets = _load_json(folder / "properties" / "psets.json")
        assert psets["Dimensions"]["thickness_mm"] == 250

    def test_template_preserves_base_psets(self, tmp_path: Path):
        template = self._make_template(tmp_path)
        output = tmp_path / "output"
        gen = ElementGenerator(output)
        folder = gen.generate_from_template(template)

        psets = _load_json(folder / "properties" / "psets.json")
        assert psets["Pset_WallCommon"]["IsExternal"] is True


# ---------------------------------------------------------------------------
# Compliance Integration
# ---------------------------------------------------------------------------

class TestComplianceIntegration:
    """Test that compliance engine integration works."""

    def test_compliance_engine_passed(self, tmp_path: Path):
        engine = ComplianceEngine()
        gen = ElementGenerator(tmp_path, compliance_engine=engine)
        spec = _wall_spec()
        folder = gen.generate(spec)
        _verify_folder_structure(folder)

    def test_non_compliant_spec_auto_adjusted(self, tmp_path: Path):
        engine = ComplianceEngine()
        gen = ElementGenerator(tmp_path, compliance_engine=engine)
        # This spec should still generate successfully
        spec = _wall_spec(properties={"thickness_mm": 50, "height_mm": 3000, "length_mm": 5000})
        folder = gen.generate(spec)
        _verify_folder_structure(folder)


# ---------------------------------------------------------------------------
# Assembly Generation
# ---------------------------------------------------------------------------

class TestAssemblyGeneration:
    """Test multi-element assembly generation."""

    def test_generate_assembly(self, tmp_path: Path):
        gen = AssemblyGenerator(tmp_path)
        specs = [
            ParametricSpec(ifc_class="IfcWall", name="Wall A", properties={"thickness_mm": 200, "height_mm": 3000, "length_mm": 5000}, materials=["concrete"]),
            ParametricSpec(ifc_class="IfcDoor", name="Door A", properties={"width_mm": 914, "height_mm": 2134}, materials=["wood"]),
        ]
        relationships = [
            {"type": "IfcRelVoidsElement", "source_index": 0, "target_index": 1},
        ]
        folder = gen.generate(specs, relationships)

        assert folder.is_dir()
        assert (folder / "assembly_manifest.json").is_file()

        manifest = _load_json(folder / "assembly_manifest.json")
        assert len(manifest["elements"]) == 2
        assert len(manifest["relationships"]) == 1
        assert manifest["relationships"][0]["type"] == "IfcRelVoidsElement"

    def test_assembly_contains_sub_elements(self, tmp_path: Path):
        gen = AssemblyGenerator(tmp_path)
        specs = [
            ParametricSpec(ifc_class="IfcWall", properties={"thickness_mm": 200, "height_mm": 3000, "length_mm": 5000}),
            ParametricSpec(ifc_class="IfcSlab", properties={"thickness_mm": 200, "length_mm": 6000, "width_mm": 6000}),
        ]
        folder = gen.generate(specs)

        # Should contain element subfolders
        element_folders = [d for d in folder.iterdir() if d.is_dir() and d.name.startswith("element_")]
        assert len(element_folders) == 2
