"""VISUALIZATION.md generation + link embedding."""

from __future__ import annotations

from pathlib import Path
from typing import Any

from aecos.visualization.exporters.base import ExportResult


def render_visualization_report(
    element_id: str,
    ifc_class: str,
    export_results: list[ExportResult],
    viewer_path: Path | None = None,
    element_folder: Path | None = None,
) -> str:
    """Render the VISUALIZATION.md content.

    Parameters
    ----------
    element_id:
        The element GlobalId.
    ifc_class:
        IFC class name.
    export_results:
        List of export results from various exporters.
    viewer_path:
        Path to the HTML viewer file, if generated.
    element_folder:
        Path to the element folder for relative link computation.
    """
    lines: list[str] = [
        f"# Visualization — {ifc_class}",
        "",
        f"**Element ID:** `{element_id}`",
        "",
        "## Available Exports",
        "",
    ]

    has_exports = False

    for result in export_results:
        if result.success and result.file_path:
            has_exports = True
            rel_path = result.file_path.name
            if element_folder and result.file_path.is_relative_to(element_folder):
                try:
                    rel_path = str(result.file_path.relative_to(element_folder))
                except ValueError:
                    rel_path = result.file_path.name

            lines.append(f"- **{result.format.upper()}**: [{rel_path}]({rel_path})")

        if result.preview_url:
            has_exports = True
            lines.append(
                f"- **{result.format.upper()} (Live)**: "
                f"[View in Browser]({result.preview_url})"
            )

    if not has_exports:
        lines.append("_No exports available._")

    lines.append("")

    # Viewer section
    if viewer_path and viewer_path.is_file():
        rel_viewer = viewer_path.name
        if element_folder:
            try:
                rel_viewer = str(viewer_path.relative_to(element_folder))
            except ValueError:
                rel_viewer = viewer_path.name

        lines.extend([
            "## Interactive Viewer",
            "",
            f"Open [{rel_viewer}]({rel_viewer}) in any modern browser "
            f"for an interactive 3D preview with orbit controls.",
            "",
        ])

    # Instructions
    lines.extend([
        "## Viewer Instructions",
        "",
        "- **Orbit**: Click and drag to rotate",
        "- **Zoom**: Scroll wheel",
        "- **Pan**: Right-click and drag",
        "",
        "---",
        "*Generated by AEC OS Visualization Bridge*",
        "",
    ])

    return "\n".join(lines)
