"""Initial rule set — hardcoded seed data for the compliance database.

NO PDF ingestion. These are representative rules covering fire ratings,
structural minimums, accessibility, energy, and egress from major codes.
Each rule has a real section citation.
"""

from __future__ import annotations

from aecos.compliance.rules import Rule

SEED_RULES: list[Rule] = [
    # -----------------------------------------------------------------------
    # FIRE RESISTANCE — IBC Chapter 7
    # -----------------------------------------------------------------------
    Rule(
        code_name="IBC2024",
        section="703.3",
        title="Fire-resistance rating required for fire barriers",
        ifc_classes=["IfcWall"],
        check_type="min_value",
        property_path="performance.fire_rating",
        check_value="1H",
        region="US",
        citation="IBC 2024 §703.3 — Fire barriers shall have a fire-resistance rating of not less than 1 hour.",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="IBC2024",
        section="706.4",
        title="Fire wall fire-resistance rating",
        ifc_classes=["IfcWall"],
        check_type="min_value",
        property_path="performance.fire_rating",
        check_value="2H",
        region="US",
        citation="IBC 2024 §706.4 — Fire walls shall have a fire-resistance rating of not less than 2 hours.",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="IBC2024",
        section="716.5",
        title="Fire door assembly rating",
        ifc_classes=["IfcDoor"],
        check_type="exists",
        property_path="performance.fire_rating",
        check_value=None,
        region="US",
        citation="IBC 2024 §716.5 — Fire door assemblies in fire barriers shall be rated.",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="CBC2025",
        section="706.4",
        title="CBC fire wall fire-resistance rating",
        ifc_classes=["IfcWall"],
        check_type="min_value",
        property_path="performance.fire_rating",
        check_value="2H",
        region="CA",
        citation="CBC 2025 §706.4 — Fire walls shall have a minimum 2-hour fire-resistance rating.",
        effective_date="2025-01-01",
    ),
    # -----------------------------------------------------------------------
    # STRUCTURAL — IBC Chapter 19 / ACI 318
    # -----------------------------------------------------------------------
    Rule(
        code_name="IBC2024",
        section="1905.1",
        title="Minimum wall thickness — concrete bearing walls",
        ifc_classes=["IfcWall"],
        check_type="min_value",
        property_path="properties.thickness_mm",
        check_value=152,
        region="US",
        citation="IBC 2024 §1905.1 / ACI 318-19 §11.3.1 — Bearing walls shall not be less than 152 mm (6 in.) thick.",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="IBC2024",
        section="1907.1",
        title="Minimum slab thickness",
        ifc_classes=["IfcSlab"],
        check_type="min_value",
        property_path="properties.thickness_mm",
        check_value=89,
        region="US",
        citation="IBC 2024 §1907.1 / ACI 318-19 §7.3.1 — Concrete floor slabs shall not be less than 89 mm (3.5 in.) thick.",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="IBC2024",
        section="2304.6",
        title="Minimum beam depth",
        ifc_classes=["IfcBeam"],
        check_type="min_value",
        property_path="properties.height_mm",
        check_value=152,
        region="US",
        citation="IBC 2024 §2304.6 — Wood beams and girders shall not be less than 152 mm (6 in.) in depth.",
        effective_date="2024-01-01",
    ),
    # -----------------------------------------------------------------------
    # ACCESSIBILITY — ADA 2010
    # -----------------------------------------------------------------------
    Rule(
        code_name="ADA2010",
        section="404.2.3",
        title="Minimum door clear width",
        ifc_classes=["IfcDoor"],
        check_type="min_value",
        property_path="properties.width_mm",
        check_value=813,
        region="US",
        citation="ADA 2010 §404.2.3 — Door openings shall provide a clear width of 813 mm (32 in.) minimum.",
        effective_date="2010-09-15",
    ),
    Rule(
        code_name="ADA2010",
        section="403.5.1",
        title="Minimum corridor clear width",
        ifc_classes=["IfcSpace"],
        check_type="min_value",
        property_path="properties.width_mm",
        check_value=915,
        region="US",
        citation="ADA 2010 §403.5.1 — Accessible routes shall have a clear width of 915 mm (36 in.) minimum.",
        effective_date="2010-09-15",
    ),
    Rule(
        code_name="ADA2010",
        section="404.2.9",
        title="Door hardware operable without tight grasping",
        ifc_classes=["IfcDoor"],
        check_type="boolean",
        property_path="constraints.accessibility.required",
        check_value=True,
        region="US",
        citation="ADA 2010 §404.2.9 — Handles, pulls, latches, locks, and other operable parts on doors shall comply with §309.4.",
        effective_date="2010-09-15",
    ),
    # -----------------------------------------------------------------------
    # ENERGY — IECC / Title 24
    # -----------------------------------------------------------------------
    Rule(
        code_name="IECC2024",
        section="C402.2",
        title="Exterior wall insulation R-value (climate zones 4-8)",
        ifc_classes=["IfcWall"],
        check_type="min_value",
        property_path="performance.thermal_r_value",
        check_value=13,
        region="US",
        citation="IECC 2024 §C402.2 — Exterior walls: minimum R-13 continuous insulation for climate zones 4-8.",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="Title-24",
        section="110.6",
        title="California exterior wall insulation requirement",
        ifc_classes=["IfcWall"],
        check_type="min_value",
        property_path="performance.thermal_r_value",
        check_value=21,
        region="CA",
        citation="Title 24 Part 6 §110.6 — Exterior walls: minimum R-21 insulation for California climate zones.",
        effective_date="2023-01-01",
    ),
    Rule(
        code_name="Title-24",
        section="120.1",
        title="California roof insulation requirement",
        ifc_classes=["IfcRoof"],
        check_type="min_value",
        property_path="performance.thermal_r_value",
        check_value=30,
        region="CA",
        citation="Title 24 Part 6 §120.1 — Roof assemblies: minimum R-30 insulation for California.",
        effective_date="2023-01-01",
    ),
    # -----------------------------------------------------------------------
    # EGRESS — IBC Chapter 10
    # -----------------------------------------------------------------------
    Rule(
        code_name="IBC2024",
        section="1005.1",
        title="Minimum corridor width for egress",
        ifc_classes=["IfcSpace"],
        check_type="min_value",
        property_path="properties.width_mm",
        check_value=1118,
        region="US",
        citation="IBC 2024 §1005.1 — The minimum width of an egress corridor shall be 1118 mm (44 in.).",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="IBC2024",
        section="1010.1.1",
        title="Minimum door width for egress",
        ifc_classes=["IfcDoor"],
        check_type="min_value",
        property_path="properties.width_mm",
        check_value=813,
        region="US",
        citation="IBC 2024 §1010.1.1 — Egress door openings shall not be less than 813 mm (32 in.) clear width.",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="IBC2024",
        section="1011.2",
        title="Minimum stair width",
        ifc_classes=["IfcStairFlight"],
        check_type="min_value",
        property_path="properties.width_mm",
        check_value=1118,
        region="US",
        citation="IBC 2024 §1011.2 — Stairways shall not be less than 1118 mm (44 in.) in width.",
        effective_date="2024-01-01",
    ),
    # -----------------------------------------------------------------------
    # Additional structural
    # -----------------------------------------------------------------------
    Rule(
        code_name="IBC2024",
        section="1607.1",
        title="Materials must be specified for structural elements",
        ifc_classes=["IfcWall", "IfcColumn", "IfcBeam", "IfcSlab", "IfcFooting"],
        check_type="exists",
        property_path="materials",
        check_value=None,
        region="US",
        citation="IBC 2024 §1607.1 — Structural elements shall have materials specified for load determination.",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="IBC2024",
        section="722.2.1",
        title="Fire-resistance rating for floor/ceiling assemblies",
        ifc_classes=["IfcSlab"],
        check_type="min_value",
        property_path="performance.fire_rating",
        check_value="1H",
        region="US",
        citation="IBC 2024 §722.2.1 — Floor/ceiling assemblies shall achieve the fire-resistance rating required by Table 601.",
        effective_date="2024-01-01",
    ),
    Rule(
        code_name="IBC2024",
        section="1015.2",
        title="Guardrail height minimum",
        ifc_classes=["IfcRailing"],
        check_type="min_value",
        property_path="properties.height_mm",
        check_value=1067,
        region="US",
        citation="IBC 2024 §1015.2 — Guards shall not be less than 1067 mm (42 in.) in height.",
        effective_date="2024-01-01",
    ),
]
